import React from 'react'
import Layout from '../components/layout'



const ServicesPage = () => {
  return (
    <Layout>
      <div>
        <h1>My services</h1>
        <p>chambray fingerstache salvia tattooed jean shorts street art put a bird on it lomo bicycle rights actually hashtag narwhal swag dreamcatcher cardigan Bushwick Godard blog pour-over irony Wes Anderson distillery Marfa keytar vegan polaroid post-ironic craft beer authentic letterpress Truffaut meh farm-to-table Williamsburg Carles raw denim pug whatever organic skateboard wayfarers you probably haven't heard of them fashion axe small batch aesthetic single-origin coffee deep v direct trade  tousled readymade normcore drinking vinegar stumptown banh mi DIY twee fap artisan scenester YOLO keffiyeh iPhone Echo Park plaid crucifix occupy viral +1 tofu leggings ugh cornhole McSweeney's forage sartorial trust fund Austin before they sold out chillwave bitters messenger bag pickled seitan Brooklyn pop-up PBR freegan art party flannel XOXO Portland hella semiotics cray Etsy fixie banjo lo-fi 90's Intelligentsia Pinterest beard selfies sustainable High Life roof party wolf mixtape gentrify typewriter synth cred Tumblr yr tote bag quinoa 8-bit American Apparel 3 wolf moon squid shabby chic kogi butcher try-hard umami kitsch Helvetica Thundercats gluten-free pork belly bespoke master cleanse four loko retro Vice Tonx asymmetrical mlkshk mustache Cosby sweater cliche paleo Pitchfork Neutra flexitarian hoodie chia biodiesel brunch fanny pack next level PBR&B gastropub locavore mumblecore selvage vinyl Odd Future disrupt Schlitz heirloom church-key slow-carb photo booth sriracha Blue Bottle Banksy Shoreditch kale chips VHS Kickstarter meggings food truck ethical literally ennui</p>
        <p>chambray fingerstache salvia tattooed jean shorts street art put a bird on it lomo bicycle rights actually hashtag narwhal swag dreamcatcher cardigan Bushwick Godard blog pour-over irony Wes Anderson distillery Marfa keytar vegan polaroid post-ironic craft beer authentic letterpress Truffaut meh farm-to-table Williamsburg Carles raw denim pug whatever organic skateboard wayfarers you probably haven't heard of them fashion axe small batch aesthetic single-origin coffee deep v direct trade  tousled readymade normcore drinking vinegar stumptown banh mi DIY twee fap artisan scenester YOLO keffiyeh iPhone Echo Park plaid crucifix occupy viral +1 tofu leggings ugh cornhole McSweeney's forage sartorial trust fund Austin before they sold out chillwave bitters messenger bag pickled seitan Brooklyn pop-up PBR freegan art party flannel XOXO Portland hella semiotics cray Etsy fixie banjo lo-fi 90's Intelligentsia Pinterest beard selfies sustainable High Life roof party wolf mixtape gentrify typewriter synth cred Tumblr yr tote bag quinoa 8-bit American Apparel 3 wolf moon squid shabby chic kogi butcher try-hard umami kitsch Helvetica Thundercats gluten-free pork belly bespoke master cleanse four loko retro Vice Tonx asymmetrical mlkshk mustache Cosby sweater cliche paleo Pitchfork Neutra flexitarian hoodie chia biodiesel brunch fanny pack next level PBR&B gastropub locavore mumblecore selvage vinyl Odd Future disrupt Schlitz heirloom church-key slow-carb photo booth sriracha Blue Bottle Banksy Shoreditch kale chips VHS Kickstarter meggings food truck ethical literally ennui</p>
      </div>
    </Layout>
  )
}
export default ServicesPage